### ISSUE TITLE
Can't find the rootViewController?

### ISSUE THREAD

**Issue by mboeddeker** [calonso/ios-arkit#6]
Has anyone heard of this issue? I'm pushing my ARController from another and I'm using the AKSideMenu?

**Comment by calonso** [comment]
I'm not sure about this issue as it sounds very generic, but it could be because you forgot setting the `rootViewController` of your app? See [the example](https://github.com/calonso/ios-arkit/blob/master/ARKit%20Example/Classes/AppDelegate.m#L20)

If it doesn't help, it could be interesting if you could provide some more context to try to help.

Regards

**Comment by calonso** [comment]
Closing as stale. Please reopen if necessary.
